---
title: "ACAT"
author: "XSun"
date: "2022-10-03"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
suppressMessages(library(ggplot2))
suppressMessages(library(gridExtra))
suppressMessages(library(data.table))
```

# Results

## Comparing ACAT p-values from real and random data (MHC included)
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE,fig.height=10, fig.width=15}
load("/project2/xinhe/xsun/CEDAR/ACAT_randomsnp_regress_peer/results/acat_real.rdata")
acat_real <- acat_allcelltypes
load("/project2/xinhe/xsun/CEDAR/ACAT_randomsnp_regress_peer/results/acat_random.rdata")
acat_random <- acat_all

type <- c("B cell (CD19+)","Monocyte (CD14+)","Leukocyte (CD15+)","Platelet","T cell (CD4+)","T cell (CD8+)")

p <- list()
for (i in 1:length(acat_random)){
  
  p_random <- acat_random[[i]]
  p_real <- acat_real[[i]]
  
  plotdata <- data.frame(observed_random = -log10(sort(as.numeric(as.character(p_random)))),
                         expected = -log10(ppoints(length(p_random))),
                         observed_real = -log10(sort(as.numeric(as.character(p_real)))) )
  dat.m <- melt(plotdata, id.vars = "expected")
  
  
  p[[i]]<- ggplot(dat.m, aes(expected, value, colour = variable)) + theme_bw(base_line_size =0.3) +
    geom_point(shape = 1, size = 1.5) +
    geom_abline(intercept = 0, slope = 1, alpha = 0.6, color = "red") +
    labs(x = expression(paste("Expected -log"[10],"(p-value)")),
         y = expression(paste("Observed -log"[10],"(p-value)"))) +
    
    theme(axis.title.x = element_text(size = 10),
          axis.text.x = element_text(size = 8, color = "black"),
          axis.title.y = element_text(size = 10),
          axis.text.y = element_text(size = 8, color = "black"),
          text= element_text(family="Times New Roman")) +
    
    scale_colour_manual(values = c("red", "steelblue")) +
    
    ggtitle(type[i]) + theme(plot.title = element_text(hjust = 0.5))
  
}

all <- grid.arrange(p[[1]],p[[2]],p[[3]],p[[4]],p[[5]],p[[6]], nrow = 2)
```



## Comparing ACAT p-values from real and random data (MHC excluded)
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE,fig.height=10, fig.width=15}
load("/project2/xinhe/xsun/CEDAR/ACAT_randomsnp_regress_peer/results/acat_real_MHCremoved.rdata")
acat_real <- acat_allcelltypes
load("/project2/xinhe/xsun/CEDAR/ACAT_randomsnp_regress_peer/results/acat_random_MHCremoved.rdata")
acat_random <- acat_all

type <- c("B cell (CD19+)","Monocyte (CD14+)","Leukocyte (CD15+)","Platelet","T cell (CD4+)","T cell (CD8+)")

p <- list()
for (i in 1:length(acat_random)){
  
  p_random <- acat_random[[i]]
  p_real <- acat_real[[i]]
  
  plotdata <- data.frame(observed_random = -log10(sort(as.numeric(as.character(p_random)))),
                         expected = -log10(ppoints(length(p_random))),
                         observed_real = -log10(sort(as.numeric(as.character(p_real)))) )
  dat.m <- melt(plotdata, id.vars = "expected")
  
  
  p[[i]]<- ggplot(dat.m, aes(expected, value, colour = variable)) + theme_bw(base_line_size =0.3) +
    geom_point(shape = 1, size = 1.5) +
    geom_abline(intercept = 0, slope = 1, alpha = 0.6, color = "red") +
    labs(x = expression(paste("Expected -log"[10],"(p-value)")),
         y = expression(paste("Observed -log"[10],"(p-value)"))) +
    
    theme(axis.title.x = element_text(size = 10),
          axis.text.x = element_text(size = 8, color = "black"),
          axis.title.y = element_text(size = 10),
          axis.text.y = element_text(size = 8, color = "black"),
          text= element_text(family="Times New Roman")) +
    
    scale_colour_manual(values = c("red", "steelblue")) +
    
    ggtitle(type[i]) + theme(plot.title = element_text(hjust = 0.5))
  
}

all <- grid.arrange(p[[1]],p[[2]],p[[3]],p[[4]],p[[5]],p[[6]], nrow = 2)
```





