---
title: "Factor Analysis"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This page is about factor analysis. Below are details of analyses. 

# **Factor Construction**

The first part of factor analysis is factor construction. We used 3 software(PLIER/PEER/FLASH) to infer expression factors from the expression matrix. 

[For more details](https://xsun1229.github.io/factor_analysis/factor_construction.html)

# **Understanding genetics of expression factors**

In this part, we're trying to answer the questions below:

- Are expression factors genetically determined? Can we build prediction model of expression factors using genetic variants?

- What are the SNPs and genes controlling expression factors?

[For more details](https://xsun1229.github.io/factor_analysis/variants_factors.html)


# **Genetic relationship between the expression factors and traits**

We'd like to show that the factors have a causal effect on outcome(traits), but it's difficult to establish.  
So we state a weaker hypothesis first: GWAS variants of a trait often converge to a relatively small number of processes, which can be represented as expression factors.

Then we strengthen hypothesis: if the effects of SNPs on LV is correlated with their effects on trait when there is a causal effect of LV on trait.

[For more details](https://xsun1229.github.io/factor_analysis/factors_traits.html)

# **Module-based factor analysis**

We used WGCNA to find modules in GTEx expression data. Then inferred some expression factors in each module with the expectation that these factor can capture the biological processes better. 

[For more details](https://xsun1229.github.io/factor_analysis/module_based_factors.html)


# **Case Studies**

Some special cases and our motivating examples are here.

[For more details](https://xsun1229.github.io/factor_analysis/case_studies.html)

